//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Reader.Presenter.Lang {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Advanced {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Advanced() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Reader.Presenter.Lang.Advanced", typeof(Advanced).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DataUI Error.
        /// </summary>
        internal static string DataUI_Error {
            get {
                return ResourceManager.GetString("DataUI_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DataUI Success.
        /// </summary>
        internal static string DataUI_Success {
            get {
                return ResourceManager.GetString("DataUI_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reboot Error.
        /// </summary>
        internal static string Reboot_Error {
            get {
                return ResourceManager.GetString("Reboot_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reboot Success.
        /// </summary>
        internal static string Reboot_Success {
            get {
                return ResourceManager.GetString("Reboot_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SetBusAddress Error.
        /// </summary>
        internal static string SetBusAddress_Error {
            get {
                return ResourceManager.GetString("SetBusAddress_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SetBusAddress Success.
        /// </summary>
        internal static string SetBusAddress_Success {
            get {
                return ResourceManager.GetString("SetBusAddress_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SetBuzzer Error.
        /// </summary>
        internal static string SetBuzzer_Error {
            get {
                return ResourceManager.GetString("SetBuzzer_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SetBuzzer Success.
        /// </summary>
        internal static string SetBuzzer_Success {
            get {
                return ResourceManager.GetString("SetBuzzer_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SetBuzzerWidth Error.
        /// </summary>
        internal static string SetBuzzerWidth_Error {
            get {
                return ResourceManager.GetString("SetBuzzerWidth_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SetBuzzerWidth Success.
        /// </summary>
        internal static string SetBuzzerWidth_Success {
            get {
                return ResourceManager.GetString("SetBuzzerWidth_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SetFrequency Error.
        /// </summary>
        internal static string SetFrequency_Error {
            get {
                return ResourceManager.GetString("SetFrequency_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SetFrequency Success.
        /// </summary>
        internal static string SetFrequency_Success {
            get {
                return ResourceManager.GetString("SetFrequency_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SetGateway Error.
        /// </summary>
        internal static string SetGateway_Error {
            get {
                return ResourceManager.GetString("SetGateway_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SetGateway Success.
        /// </summary>
        internal static string SetGateway_Success {
            get {
                return ResourceManager.GetString("SetGateway_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SetIpAddress Error.
        /// </summary>
        internal static string SetIpAddress_Error {
            get {
                return ResourceManager.GetString("SetIpAddress_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SetIpAddress Success.
        /// </summary>
        internal static string SetIpAddress_Success {
            get {
                return ResourceManager.GetString("SetIpAddress_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SetMacAddress Error.
        /// </summary>
        internal static string SetMacAddress_Error {
            get {
                return ResourceManager.GetString("SetMacAddress_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SetMacAddress Success.
        /// </summary>
        internal static string SetMacAddress_Success {
            get {
                return ResourceManager.GetString("SetMacAddress_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SetMask Error.
        /// </summary>
        internal static string SetMask_Error {
            get {
                return ResourceManager.GetString("SetMask_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SetMask Success.
        /// </summary>
        internal static string SetMask_Success {
            get {
                return ResourceManager.GetString("SetMask_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SetModel Error.
        /// </summary>
        internal static string SetModel_Error {
            get {
                return ResourceManager.GetString("SetModel_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SetModel Success.
        /// </summary>
        internal static string SetModel_Success {
            get {
                return ResourceManager.GetString("SetModel_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SetName Error.
        /// </summary>
        internal static string SetName_Error {
            get {
                return ResourceManager.GetString("SetName_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SetName Success.
        /// </summary>
        internal static string SetName_Success {
            get {
                return ResourceManager.GetString("SetName_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SetPower Error.
        /// </summary>
        internal static string SetPower_Error {
            get {
                return ResourceManager.GetString("SetPower_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SetPower Success.
        /// </summary>
        internal static string SetPower_Success {
            get {
                return ResourceManager.GetString("SetPower_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SetRs232BaudRate Error.
        /// </summary>
        internal static string SetRs232BaudRate_Error {
            get {
                return ResourceManager.GetString("SetRs232BaudRate_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SetRs232BaudRate Success.
        /// </summary>
        internal static string SetRs232BaudRate_Success {
            get {
                return ResourceManager.GetString("SetRs232BaudRate_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SetSerialNumber Error.
        /// </summary>
        internal static string SetSerialNumber_Error {
            get {
                return ResourceManager.GetString("SetSerialNumber_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SetSerialNumber Success.
        /// </summary>
        internal static string SetSerialNumber_Success {
            get {
                return ResourceManager.GetString("SetSerialNumber_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SetSocketPortTcp Error.
        /// </summary>
        internal static string SetSocketPortTcp_Error {
            get {
                return ResourceManager.GetString("SetSocketPortTcp_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SetSocketPortTcp Success.
        /// </summary>
        internal static string SetSocketPortTcp_Success {
            get {
                return ResourceManager.GetString("SetSocketPortTcp_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SetSocketPortUdp Error.
        /// </summary>
        internal static string SetSocketPortUdp_Error {
            get {
                return ResourceManager.GetString("SetSocketPortUdp_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SetSocketPortUdp Success.
        /// </summary>
        internal static string SetSocketPortUdp_Success {
            get {
                return ResourceManager.GetString("SetSocketPortUdp_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SetTagFilter Error.
        /// </summary>
        internal static string SetTagFilter_Error {
            get {
                return ResourceManager.GetString("SetTagFilter_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SetTagFilter Success.
        /// </summary>
        internal static string SetTagFilter_Success {
            get {
                return ResourceManager.GetString("SetTagFilter_Success", resourceCulture);
            }
        }
    }
}
