//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Reader.Presenter.Lang {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Main {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Main() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Reader.Presenter.Lang.Main", typeof(Main).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect Error.
        /// </summary>
        internal static string Connect_Error {
            get {
                return ResourceManager.GetString("Connect_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect Success.
        /// </summary>
        internal static string Connect_Success {
            get {
                return ResourceManager.GetString("Connect_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disconnect Error.
        /// </summary>
        internal static string Disconnect_Error {
            get {
                return ResourceManager.GetString("Disconnect_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disconnect Success.
        /// </summary>
        internal static string Disconnect_Success {
            get {
                return ResourceManager.GetString("Disconnect_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ReadStart Error.
        /// </summary>
        internal static string ReadStart_Error {
            get {
                return ResourceManager.GetString("ReadStart_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ReadStart Success.
        /// </summary>
        internal static string ReadStart_Success {
            get {
                return ResourceManager.GetString("ReadStart_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ReadStop Error.
        /// </summary>
        internal static string ReadStop_Error {
            get {
                return ResourceManager.GetString("ReadStop_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ReadStop Success.
        /// </summary>
        internal static string ReadStop_Success {
            get {
                return ResourceManager.GetString("ReadStop_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reconnect Error.
        /// </summary>
        internal static string Reconnect_Error {
            get {
                return ResourceManager.GetString("Reconnect Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reconnect Success.
        /// </summary>
        internal static string Reconnect_Success {
            get {
                return ResourceManager.GetString("Reconnect_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SetBuzzer Error.
        /// </summary>
        internal static string SetBuzzer_Error {
            get {
                return ResourceManager.GetString("SetBuzzer_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SetBuzzer Success.
        /// </summary>
        internal static string SetBuzzer_Success {
            get {
                return ResourceManager.GetString("SetBuzzer_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SetMysql Error.
        /// </summary>
        internal static string SetMysql_Error {
            get {
                return ResourceManager.GetString("SetMysql_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SetMysql Success.
        /// </summary>
        internal static string SetMysql_Success {
            get {
                return ResourceManager.GetString("SetMysql_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SetPower Error.
        /// </summary>
        internal static string SetPower_Error {
            get {
                return ResourceManager.GetString("SetPower_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SetPower Success.
        /// </summary>
        internal static string SetPower_Success {
            get {
                return ResourceManager.GetString("SetPower_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SetSound Error.
        /// </summary>
        internal static string SetSound_Error {
            get {
                return ResourceManager.GetString("SetSound_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SetSound Success.
        /// </summary>
        internal static string SetSound_Success {
            get {
                return ResourceManager.GetString("SetSound_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SetTagFilter Error.
        /// </summary>
        internal static string SetTagFilter_Error {
            get {
                return ResourceManager.GetString("SetTagFilter_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SetTagFilter Success.
        /// </summary>
        internal static string SetTagFilter_Success {
            get {
                return ResourceManager.GetString("SetTagFilter_Success", resourceCulture);
            }
        }
    }
}
