//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Reader.View.Lang {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Advanced {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Advanced() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Reader.View.Lang.Advanced", typeof(Advanced).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bus Address (0 - 255).
        /// </summary>
        internal static string BusAddressContainer {
            get {
                return ResourceManager.GetString("BusAddressContainer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        internal static string Button {
            get {
                return ResourceManager.GetString("Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buzzer (0 - 1).
        /// </summary>
        internal static string BuzzerContainer {
            get {
                return ResourceManager.GetString("BuzzerContainer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buzzer Width (1 - 255).
        /// </summary>
        internal static string BuzzerWidthContainer {
            get {
                return ResourceManager.GetString("BuzzerWidthContainer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DataUI Error.
        /// </summary>
        internal static string DataUI_Error {
            get {
                return ResourceManager.GetString("DataUI_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DataUI Success.
        /// </summary>
        internal static string DataUI_Success {
            get {
                return ResourceManager.GetString("DataUI_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced.
        /// </summary>
        internal static string FormName {
            get {
                return ResourceManager.GetString("FormName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frequency (0 - 23).
        /// </summary>
        internal static string FrequencyContainer {
            get {
                return ResourceManager.GetString("FrequencyContainer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gateway (IPv4).
        /// </summary>
        internal static string GatewayContainer {
            get {
                return ResourceManager.GetString("GatewayContainer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IP Address (IPv4).
        /// </summary>
        internal static string IpAddressContainer {
            get {
                return ResourceManager.GetString("IpAddressContainer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MAC Address (12 chars).
        /// </summary>
        internal static string MacAddressContainer {
            get {
                return ResourceManager.GetString("MacAddressContainer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mask (IPv4).
        /// </summary>
        internal static string MaskContainer {
            get {
                return ResourceManager.GetString("MaskContainer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model (6 chars).
        /// </summary>
        internal static string ModelContainer {
            get {
                return ResourceManager.GetString("ModelContainer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name (8 chars).
        /// </summary>
        internal static string NameContainer {
            get {
                return ResourceManager.GetString("NameContainer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Power (0 - 15).
        /// </summary>
        internal static string PowerContainer {
            get {
                return ResourceManager.GetString("PowerContainer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reboot.
        /// </summary>
        internal static string RebootContainer {
            get {
                return ResourceManager.GetString("RebootContainer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Baud Rate (0 - 5).
        /// </summary>
        internal static string Rs232BaudRateContainer {
            get {
                return ResourceManager.GetString("Rs232BaudRateContainer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serial Number (8 chars).
        /// </summary>
        internal static string SerialNumberContainer {
            get {
                return ResourceManager.GetString("SerialNumberContainer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TCP Port Number (1024 - 65535).
        /// </summary>
        internal static string SocketPortTcpContainer {
            get {
                return ResourceManager.GetString("SocketPortTcpContainer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UDP Port Number (1024 - 65535).
        /// </summary>
        internal static string SocketPortUdpContainer {
            get {
                return ResourceManager.GetString("SocketPortUdpContainer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.
        /// </summary>
        internal static string TabControlPage1 {
            get {
                return ResourceManager.GetString("TabControlPage1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Communication.
        /// </summary>
        internal static string TabControlPage2 {
            get {
                return ResourceManager.GetString("TabControlPage2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TagFilter (0 - 255).
        /// </summary>
        internal static string TagFilterContainer {
            get {
                return ResourceManager.GetString("TagFilterContainer", resourceCulture);
            }
        }
    }
}
