//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Reader.View.Lang {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Main {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Main() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Reader.View.Lang.Main", typeof(Main).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect.
        /// </summary>
        internal static string ConnectionComConnect {
            get {
                return ResourceManager.GetString("ConnectionComConnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection COM (Connection ID, Bus Address, COM Port, Baud Rate).
        /// </summary>
        internal static string ConnectionComContainer {
            get {
                return ResourceManager.GetString("ConnectionComContainer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disconnect.
        /// </summary>
        internal static string ConnectionComDisconnect {
            get {
                return ResourceManager.GetString("ConnectionComDisconnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect.
        /// </summary>
        internal static string ConnectionIpConnect {
            get {
                return ResourceManager.GetString("ConnectionIpConnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection IP (Connection ID, Protocol, IP Address, Port).
        /// </summary>
        internal static string ConnectionIpContainer {
            get {
                return ResourceManager.GetString("ConnectionIpContainer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disconnect.
        /// </summary>
        internal static string ConnectionIpDisconnect {
            get {
                return ResourceManager.GetString("ConnectionIpDisconnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reader.
        /// </summary>
        internal static string FormName {
            get {
                return ResourceManager.GetString("FormName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device Log.
        /// </summary>
        internal static string LogDeviceContainer {
            get {
                return ResourceManager.GetString("LogDeviceContainer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID.
        /// </summary>
        internal static string LogDeviceListViewColumnId {
            get {
                return ResourceManager.GetString("LogDeviceListViewColumnId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to null.
        /// </summary>
        internal static string LogDeviceListViewColumnNull {
            get {
                return ResourceManager.GetString("LogDeviceListViewColumnNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time.
        /// </summary>
        internal static string LogDeviceListViewColumnTime {
            get {
                return ResourceManager.GetString("LogDeviceListViewColumnTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value.
        /// </summary>
        internal static string LogDeviceListViewColumnValue {
            get {
                return ResourceManager.GetString("LogDeviceListViewColumnValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transponder Log.
        /// </summary>
        internal static string LogTransponderContainer {
            get {
                return ResourceManager.GetString("LogTransponderContainer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activator.
        /// </summary>
        internal static string LogTransponderListViewColumnActivator {
            get {
                return ResourceManager.GetString("LogTransponderListViewColumnActivator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Battery.
        /// </summary>
        internal static string LogTransponderListViewColumnBattery {
            get {
                return ResourceManager.GetString("LogTransponderListViewColumnBattery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID.
        /// </summary>
        internal static string LogTransponderListViewColumnId {
            get {
                return ResourceManager.GetString("LogTransponderListViewColumnId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to null.
        /// </summary>
        internal static string LogTransponderListViewColumnNull {
            get {
                return ResourceManager.GetString("LogTransponderListViewColumnNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number.
        /// </summary>
        internal static string LogTransponderListViewColumnNumber {
            get {
                return ResourceManager.GetString("LogTransponderListViewColumnNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RSSI 1.
        /// </summary>
        internal static string LogTransponderListViewColumnRssi1 {
            get {
                return ResourceManager.GetString("LogTransponderListViewColumnRssi1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RSSI 2.
        /// </summary>
        internal static string LogTransponderListViewColumnRssi2 {
            get {
                return ResourceManager.GetString("LogTransponderListViewColumnRssi2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value.
        /// </summary>
        internal static string LogTransponderListViewColumnValue {
            get {
                return ResourceManager.GetString("LogTransponderListViewColumnValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read.
        /// </summary>
        internal static string ReadContainer {
            get {
                return ResourceManager.GetString("ReadContainer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        internal static string ReadReset {
            get {
                return ResourceManager.GetString("ReadReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        internal static string ReadStart {
            get {
                return ResourceManager.GetString("ReadStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop.
        /// </summary>
        internal static string ReadStop {
            get {
                return ResourceManager.GetString("ReadStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced.
        /// </summary>
        internal static string SettingsHwAdvanced {
            get {
                return ResourceManager.GetString("SettingsHwAdvanced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hardware Settings (Power, TagFilter, Buzzer).
        /// </summary>
        internal static string SettingsHwContainer {
            get {
                return ResourceManager.GetString("SettingsHwContainer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Software Settings (Activator, TagFilter, RSSI 1, RSSI 2, Sound, MySQL).
        /// </summary>
        internal static string SettingsSwContainer {
            get {
                return ResourceManager.GetString("SettingsSwContainer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MySQL.
        /// </summary>
        internal static string SettingSwMysql {
            get {
                return ResourceManager.GetString("SettingSwMysql", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sound.
        /// </summary>
        internal static string SettingSwSound {
            get {
                return ResourceManager.GetString("SettingSwSound", resourceCulture);
            }
        }
    }
}
